language: csharp
solution: ArrayExtensions.sln
mono: none
dotnet: 1.1.5
install:
  - dotnet restore
  - nuget
  - nuget restore ArrayExtensions.sln -Verbosity detailed
  - nuget update ArrayExtensions.sln -Verbosity detailed
  - nuget install xunit.runner.console -Version 2.3.1 -OutputDirectory testrunner
  - nuget install FsCheck -Version 2.10.8 -OutputDirectory testrunner
  - nuget install FsCheck.Xunit -Version 2.10.8 -OutputDirectory testrunner
 script:
  - xbuild /p:Configuration=Release ArrayExtensions.sln
  - mono ./testrunner/xunit.runner.console.*/tools/xunit.console.exe ./Tests/bin/Release/ArrayExtensions.Tests.dll
  